import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { getServerSession } from "next-auth";
import { authConfig } from "@/src/shared/config/authConfig";
import { getMessages, getTimeZone, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  setRequestLocale(locale);
  const [messages, timeZone, session] = await Promise.all([
    getMessages(),
    getTimeZone(),
    getServerSession(authConfig),
  ]);
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Providers
          session={session}
          messages={messages}
          locale={locale}
          timeZone={timeZone}
        >
          {children}
        </Providers>
      </body>
    </html>
  );
}
